# Generated by Django 4.1.1 on 2023-05-30 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KuderTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('result', models.CharField(choices=[('exterior', 'Exterior'), ('mecanica', 'Mecánica'), ('calculo', 'Cálculo'), ('cientifica', 'Científica'), ('persuasiva', 'Persuasiva'), ('artistica', 'Artística'), ('literaria', 'Literaria'), ('musical', 'Musical'), ('servicio', 'Servicio'), ('oficina', 'Oficina')], max_length=50, verbose_name='result')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
